### PR TITLE
Configure docs ready for Travis

### PR DESCRIPTION
**Pull request by Libbum**
Saw you were having trouble getting docs to build. This is how I'd set them up&mdash;assuming you have the travis/codecov side of things sorted, I expect this to pass tests at least. 

The docs pages 'build' for me locally, but since you don't have any written for the moment, there's not much to populate of course :smile:

### CODE REVIEW

**Comment by Libbum** [comment]
Well, looks like your master branch may have some issues with packages: `MakieRecipes` is not found.

**Comment by kool7d** [comment]
I had a broken package in the Project

**Comment by Libbum** [comment]
You've got some restrictions in Project.toml that can't be satisfied in Julia v1.0. I'll allow failures there for the moment.

**Comment by kool7d** [comment]
Is that because they rely on packages that use stuff from other packages that may use features from 1.5 that aren't in 1.0? So they have their own compat restrictions that are too high?

**Comment by Libbum** [comment]
Something like that, yeah. 
> ERROR: Unsatisfiable requirements detected for package CairoMakie [13f3f980]:
> CairoMakie [13f3f980] log:
> ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.3, 0.2.0-0.2.9, 0.3.0-0.3.3] or uninstalled
> ├─restricted to versions 0.3.0-0.3 by an explicit requirement, leaving only versions 0.3.0-0.3.3
> └─restricted by julia compatibility requirements to versions: [0.0.1-0.0.2, 0.1.0-0.1.2] or uninstalled — no versions left

So if `CairoMakie` needs > 1 in v0.3+, then you can't tag that version...

**Comment by Libbum** [comment]
I've droped GLMakie and WGLMakie and CairoMakie as dependencies here, since you're developing a library and want to give users the freedom to set up and use it how they wish. Looks like, for the most part you want to rely on `AbstractPlotting`. Take a look at how [InteractiveChaos](https://github.com/JuliaDynamics/InteractiveChaos.jl) works for example.

For interactions, when you need a GL backend then you can suggest
```julia
using BioMakie, GLMakie
```
in the docs.

I'd say this is really how you want to develop this package, but primarily I did this since I'm not even sure it's possible to build GLMakie on Travis at all... 

If that's something you're not happy with, or can't work with, then getting the package to function on Travis is a bit outside my wheelhouse. GLMakie itself seems to build fine using [gitlab-ci](https://github.com/JuliaPlots/GLMakie.jl/blob/master/.gitlab-ci.yml), so perhaps that's something to investigate?

Otherwise, looks like things are building just fine now. When you merge, you may want to squash this PR - I made a bit of a mess of it sorry. One thing you'll need to do before the automatic push works is add the [`DOCUMENTER_KEY`](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh).

**Pull request merged**
